# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtWidgets import QMainWindow, QWidget


class Ui_TaskTreeMain(object):
    def setupUi(self, TaskTreeMain):
        TaskTreeMain.setObjectName("TaskTreeMain")
        TaskTreeMain.resize(574, 474)
        self.centralwidget = QtWidgets.QWidget(parent=TaskTreeMain)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")

        self.verticalLayout.addWidget(self.treeWidget)
        TaskTreeMain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TaskTreeMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 574, 22))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        TaskTreeMain.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TaskTreeMain)
        self.statusbar.setObjectName("statusbar")
        TaskTreeMain.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(TaskTreeMain)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtWidgets.QAction(TaskTreeMain)
        self.actionLoad.setObjectName("actionLoad")
        self.actionExit = QtWidgets.QAction(TaskTreeMain)
        self.actionExit.setObjectName("actionExit")
        self.menuMenu.addAction(self.actionSave)
        self.menuMenu.addAction(self.actionLoad)
        self.menuMenu.addAction(self.actionExit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(TaskTreeMain)
        QtCore.QMetaObject.connectSlotsByName(TaskTreeMain)

    def retranslateUi(self, TaskTreeMain):
        _translate = QtCore.QCoreApplication.translate
        TaskTreeMain.setWindowTitle(_translate("TaskTreeMain", "TaskTreeMain"))
        self.menuMenu.setTitle(_translate("TaskTreeMain", "Menu"))
        self.actionSave.setText(_translate("TaskTreeMain", "Save"))
        self.actionLoad.setText(_translate("TaskTreeMain", "Load"))
        self.actionExit.setText(_translate("TaskTreeMain", "Exit"))
